apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-webapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-webapi
  template:
    metadata:
      labels:
        app: dotnet-webapi
    spec:
      containers:
      - name: dotnet-webapi
        image: twoj-login-github/projekt-devops:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-webapi-service
spec:
  type: LoadBalancer
  selector:
    app: dotnet-webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080